README.md
=> fix: update pr build process

package.json
=> Helix-React v1.0.0-alpha.0

package.json
=> feat(build): 1.0.0-alpha.1 [skip ci]

package.json
=> chore(patch): bump version [skip ci]

package.json
=> publish(npm): v1.0.0-alpha.3 [skip ci]

package.json
=> build(patch): fix file typo

package.json
=> publish(npm): v1.0.0-alpha.4

package.json, yarn.lock
Package size is now reasonably small.
It likely is possible to get this working with Parcel especially v2, and it would decrease build times, but this micro bundle project seems to centered around making bundles smaller, which might be more ideal in our case since we do not suffer from long build times given the nature and size of this project. Parcel did not have very good docs that I could find around building libraries.
=> Bundled With MicroBundle

package.json
Bump version: Helix-React v1.0.0 (alpha release)
=> publish(npm): v1.0.0 alpha release [skip ci]

README.md, package.json, src/index.mjs, yarn.lock
Make is so you can import in a standard way ie:
import { Alert } from '@helix-design-system/helix-react/';
=> Fix importing 

package.json
=> feat(release): helix-react v1.2.0 alpha release [skip ci]

README.md, package.json
=> Fix for missing dist folder

package.json
=> publish(npm): v1.3.0 [skip ci]

package.json
=> publish(npm): v1.4.0

README.md
=> docs(readme): update status of release

package.json
=> publish(npm): v2.0.0

src/Tooltip/stories.js
Docs currently have an error, because React is missing, this PR fixes the issue.
=> Fix error in docs

src/PasswordText/index.js, src/PasswordText/stories.js
=> feat(password): implement input type='password' capability

package.json
=> publish(npm): v2.1.0

src/index.mjs
Export Password Component.
I guess i forgot to export the password component.
=> fix(password)- export password compoenent
